### ISSUE TITLE
A Github tab

### ISSUE THREAD

**Issue by roonyh** [roonyh/fossasia-gci-companion#15]
Currently there are two tabs regarding **Global Git Confuguration** and the **GCI 15 website**

Add another tab **Github**

When users switch to that tab Github login dialog should be displayed. This is currently done by pressing the LOG IN button on **Global Git Config** tag. Code is in: https://github.com/roonyh/fossasia-gci-companion/blob/master/lib/oAuthGithub.js

After the login users information and avatar should be displayed.

**Comment by YagoGG** [comment]
I'd like to work on this issue!
BTW, which template engine should be used?

**Comment by roonyh** [comment]
@YagoGG Great!! Thanks for your interest!

I am not sure how easy it is to get a template engine working here with electron. Would jade work? If so I like it. Do what is easier for you.

**Comment by YagoGG** [comment]
In a quick search I found [electron-jade](https://www.npmjs.com/package/electron-jade), which should allow us to use Jade with Electron, and looks good to me.
However, I don't know if there's any better way to dynamically generate HTML in Electron.

**Comment by roonyh** [comment]
electron-jade looks easy enogh! lets go with it :)

**Comment by YagoGG** [comment]
Should I migrate the whole `index.html` to Jade, or make an `<iframe>`/[`<webview>`](http://electron.atom.io/docs/v0.30.0/api/web-view-tag/) inside each tab that requires dynamic content, displaying a `.jade` file inside?

**Comment by roonyh** [comment]
Using iframes or webviews to show content from our own site doesn't feel right. So migrate the whole index html file.

**Comment by YagoGG** [comment]
After adding `const jade = require('electron-jade')();` at the top of `main.js`, and setting `indexUrl` as:

``` javascript
var indexUrl = "file://" + __dirname + "/index.jade";
```

I get the following error on Chrome's dev console after starting the app with `npm start`:

> Not allowed to load local resource: file://<path>/fossasia-gci-companion/index.jade

`index.jade` exists and it has the same permissions as `index.html` (644, _AKA_ `rw-rw-r--`). Setting them to 777 doesn't help either.

I can't apply the fix on [this issue](https://github.com/yan-foto/electron-jade/issues/4) because downgrading [would break everyting](https://github.com/yan-foto/electron-jade/issues/4#issuecomment-133688218).

`electron-jade` docs (just [the README](https://github.com/yan-foto/electron-jade/blob/master/README.md)) don't mention this error.

Any ideas?

**Comment by roonyh** [comment]
What is the electron-jade version? Could you try updating to the latest? (1.3.0)

Also make a PR with the code you have currently. I like to try this, it would be easier to find a fix if we both have the code.

**Comment by roonyh** [comment]
@YagoGG So I tried this and had the same issue. But I had better luck with electron-jade version **1.2.0**  

I think that is the version that is compatible with our electron prebuilt version.

I guess you know how to use a specific version of an npm module?

just in case add `"electron-jade": "1.2.0",` to `package.json` and remove the `node_modules` folder and `npm install`

I'll be online on IRC for about 3 more hours if you need me :)

**Comment by roonyh** [comment]
I noticed I get the same issue as this when I remove the jade file.
![download](https://cloud.githubusercontent.com/assets/3872221/12334750/abaf7d4a-bb21-11e5-8857-537d96824a6b.png) 

So I guess the __directory is not set properly in your machine and its not able to find the jade file.
try hardcoding the indexUrl. Something like

`var indexUrl = "file:///Users/aruna/gci/fossasia-gci-companion/index.jade"`

**Comment by YagoGG** [comment]
It didn't work :S

**Comment by roonyh** [comment]
:(

Ok, we'll figure this out later.

**Comment by roonyh** [comment]
I figured out that the latest version (**1.3.0**) works perfectly fine when jade file compiles. :)  The error we get is because it does not compile successfully.

Try it with a simple jade file first.

It just does not give a proper error feedback. [Add a console.error](https://github.com/roonyh/electron-jade/blob/master/index.js#L43) to get the error output.

**Comment by roonyh** [comment]
Make sure you remove node_modules before installing **1.3.0**

**Comment by YagoGG** [comment]
That was BRILLIANT!

After setting a valid Jade file, I also had problems regarding my file structure: it seems it doesn't get along well with paths with spaces/accents (yeah, I know I shouldn't have directories with any of them but, you know...).  
Using a valid path solved the other issues and, as you said, now I can run it using **electron-jade v1.3.0 with a valid Jade file**.  
I'll get back to work!

**Comment by YagoGG** [comment]
Okay, here's the deal:

After making another `require()` call for _electron-jade_, this time with the data collected from GitHub's API, the Jade content is unable to access the locals (I checked it with an `if` statement). See https://github.com/YagoGG/fossasia-gci-companion/commit/7b1109b7dee992d6bcb2b19c13f8c81c8ffd5d85 for the whole context.

So, after some code-diving and research, I found out that when `var jade = require('electron-jade')()` is called, it waits for the [`app`](http://electron.atom.io/docs/v0.30.0/api/app/) to be ready, and then sets the interceptor for all requests with the protocol `file://`, to look for files with extension `.jade`.

The problem is that, because of `app.on('ready' [...])` is just triggered once, locals can be set only at the very first call of _electron-jade_. Therefore, future ones won't be able to modify the interceptor, and the locals will remain empty.

From _electron-jade_'s [source code](https://github.com/yan-foto/electron-jade/blob/master/index.js#L22-L53):

``` javascript
module.exports = function(jadeOptions, locals) {
  app.on('ready', function() {
    var protocol = require('protocol');
    var options = extend({}, jadeOptions || {});

    protocol.interceptBufferProtocol('file', function(request, callback) {
      var file = getPath(request.url);
      var content = null;

      // See if file actually exists
      try {
        content = fs.readFileSync(file);

        var ext = path.extname(file);
        if (ext === '.jade') {
          var compiled = jade.compileFile(file, jadeOptions)(locals);
```

Maybe a possible workaround could be to place after the event listener this:

``` javascript
if(app_is_ready) {
  protocol.uninterceptProtocol('jade', function() {
    protocol.interceptBufferProtocol('jade', function(request, callback) {
      // set the interceptor again, with the new locals...
    });
  });
}
```

However, I haven't been able to find any way to check if app's `ready` event has already been triggered (which is the condition `app_is_ready`), and I'm not even sure if the code before would fix the problem.

Which should be the next step?

**Comment by roonyh** [comment]
Ok, So `'electron-jade'`'s job is to intercept when a window is created with a `file://` url and render jade. That is very nice for the main thread. (When the app starts.) But when the app starts and enters the renderer process its not much useful. Because at that point we can directly use regular [jade] package (https://www.npmjs.com/package/jade)

Let's keep static content, (data that is available to us when the app starts) in the index.jade file. And take templates that we need dinamic data to render into separte template files.

So we will have a github.jade file. When the data becomes available we will render it using normal jade package and put it in right place using `document.getElementById('github-data').innerHTML = renderedHTML`

in index.jade we have some place holder. The one you have now saying "You are not logged in" is good.

Does this sound good?

**Comment by YagoGG** [comment]
Yeah, sounds good to me.

But if we are going to use directly the _jade_ package, why not reloading the page as we were already trying? I'm not sure if you can render content without `header`, `body`, etc. If we can do it, great, but if we can't, it would be like having an `iframe` in the application.

The procedure could be the following:
1. Load `index.jade` when the app starts, without any locals
2. The page is shown with the _static_ content
3. When the user authenticates, we reload `index.jade`, but this time with the `github` object as local

Which one do you prefer?

**Comment by roonyh** [comment]
Reloading the page renders everything again. Why do that when we can render just the part we want? :)

Its possible to render partials of pages, without `head`, `body`, with jade

We will follow just that procedure except at step 3 render the part of github tab.
